pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  displayName: Use Node.js LTS version
  inputs:
    versionSpec: '10.x'

- script: yarn install
  displayName: Install dependencies

- script: yarn build
  displayName: Build application

- script: yarn test:ci
  displayName: Run tests

- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testResultsFiles: 'junit.xml'

- task: PublishPipelineArtifact@1
  displayName: Publish build artifacts
  inputs:
    artifact: dist
