pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: yarn install

- script: yarn build

- task: PublishPipelineArtifact@0
  inputs:
    targetPath: dist
